### ISSUE TITLE
dynamically link the map, line plot, and select box

### ISSUE THREAD

**Issue by davemfish** [davemfish/trails-viz#1]
Right now the select box and line plot are populated by data from the same csv file, but the map lines have a different data source (geojson). It would be nice to link them all, so that the line plot would update either by changing the select box or clicking on a line on the map. Similarly, the select box could trigger a pan and zoom on the map to the selected trail.

A solution might require loading data files (csv and geojson) in a scope that is available to both the leaflet and line-plot functions. And that might avoid redundant data (e.g. a trail name field) that might appear in both files now.

**Comment by davemfish** [comment]
This is working great! As we already discussed, the finishing touch here is a way to preserve the highlighting of the line segment after it's clicked. That way the trail being displayed in the chart will always be highlighted on the map.

**Comment by woodsp** [comment]
And similarly, I think it would be nice if trails were highlighted on the map after being selected in the drop-down box.

**Comment by davemfish** [comment]
It looks like trails already do stay highlighted after select box changes.
