### ISSUE TITLE
Beautify

### ISSUE THREAD

**Issue by woodsp** [davemfish/trails-viz#18]
Style the website -- initially with the minimum elements required to make it look semi-professional.  

To start, I'm guessing that means a header, footer, nav(?), and more user-friendly arrangement of maps and graphs.  A tagline or short project description might also be nice.

We're branding it SocialTrails for now, until we come up with a better (good?) name.

**Comment by davemfish** [comment]
Here's some assorted ideas...

Header - I guess a title bar that says "SocialTrails", and room to add a tagline next to it.
Footer - not sure what goes here, some fine-print about who we are, links to other content.
Arrangement - the main improvement would be to let the map always fill the width of the screen. I think the timeseries plot under the map works well, both map and timeseries are well-suited to a landscaped layout. Maybe histogram could be small and alongside the line plot. Not sure where the dropdown goes...

**Comment by davemfish** [comment]
Closing this since we accomplished our first set of goals. Feel free to re-open later if we need to do another round of "beautifying".
